name: Build dynamic library file

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - LICENSE
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - LICENSE
      - README.md

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1.5.0
        with:
          pkg: cmd/tlssocksproxy
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: tlssocks
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64,android/arm64,android/arm
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
